name: Rancher Gluster
description: |
  Docker volume plugin for gluster.
version: 0.2.2
category: Storage
labels:
  io.rancher.certified: Experimental
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
