version: '2'
services:
  gluster-driver:
    privileged: true
    image: 10.1.241.80:5000/rancher/storage-gluster:p2
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
    environment:
      GLUSTER_SERVER: '${GLUSTER_SERVER}'
    volumes:
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
