.catalog:
  name: "Rancher Gluster"
  version: "0.2.1"
  description: |
    Docker volume plugin for GLUSTERFS
  minimum_rancher_version: v1.1.99
  maximum_rancher_version: v1.3.99
  questions:
  - variable: "GLUSTER_SERVER"
    description: "IP or hostname of the glusterfs Server"
    label: "GLUSTER Server"
    required: true
    type: "string"
  - variable: RANCHER_DEBUG
    label: Debug Mode
    type: enum
    description: Enable or disable verbose logging
    default: false
    options:
    - true
    - false
gluster-driver:
  storage_driver:
    name: rancher-gluster
    scope: environment
    volume_access_mode: multiHostRW
